name: ARC smoke test

on:
  workflow_dispatch: {}

jobs:
  smoke:
    name: Run on ARC runner
    runs-on: k3s-arc
    steps:
      - name: Hello
        run: |
          echo "Hello from ARC runner!"
          uname -a
          id
